### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by cmaguilera** [Bonitasoft-Community/page_log#2]
Version BonitaBPMCommunity-7.4.3
Hello. When i use the page in an app i have these errors:

/home/carlos/BonitaBPMCommunity-7.4.3/workspace/tomcat/server/temp/bonita_portal_11656@carlos-laptop/tenants/1/-2136707345/Index.groovy: 46: unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 @ line 46, column 1.
   import com.bonitasoft.engine.api.PlatformMonitoringAPI;

2017-03-13 13:42:23.107 +0100 ADVERTENCIA: org.bonitasoft.livingapps.LivingApplicationPageServlet Error while trying to render the application page custompage_log
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/carlos/BonitaBPMCommunity-7.4.3/workspace/tomcat/server/temp/bonita_portal_11656@carlos-laptop/tenants/1/pages/custompage_log/Index.groovy: 41: unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 @ line 41, column 1.
   import com.bonitasoft.engine.api.TenantAPIAccessor;

Thank you!!

Best regards!

Carlos

**Comment by pierre-yves-monnet** [comment]
Hello,
THis issue should be fixed in version 1.1 : do you use this one ?
