### ISSUE TITLE
page_log don't work

### ISSUE THREAD

**Issue by etchegaray** [Bonitasoft-Community/page_log#5]
I don't know if this i the apropiate place for my question.
I try to use this page_log in bonita 7.5.4 and the page is showed but when click on a log "An error ocured". It's posible that don't work in this version. 

Something similar happens with "page_startprocess", "custom page Awacs" and "custom_page Longboard" (and these cases support BonitaBPM version 7.x)

Thank you

**Comment by pierre-yves-monnet** [comment]
Hello,
Thanks you to point this.
Bonita 7.5 use the last Tomcat release, which change the URL parameters policy.
An upgrade for 7.5 will be release soon

**Comment by etchegaray** [comment]
Thank you. I'll wait for that release.

**Comment by pierre-yves-monnet** [comment]
Ready for 7.5 now

**Comment by etchegaray** [comment]
Pierre,

I'm sorry but I just downloaded and installed the lastest version and it don't work: error 500.

Thanks

Javier

**Comment by pierre-yves-monnet** [comment]
Hello,
Thanks for your return. 
It's works correctly in 7.5.4 with the subscription / Tomcat version. Could you send me the log you have ? I assume you use a community version ?

**Comment by pierre-yves-monnet** [comment]
I try and reproduce in the community version. Version is published,
